<!DOCTYPE html>
<html lang="nl_NL">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mozart op Zaterdag</title>
</head>

<body>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);"><span style="font-family: Arial, Helvetica, sans-serif;">Ik vind dit een erg leuke en inspirerende formule, die me aanzet om iets vergelijkbaars te bedenken: <i>Mozart op Zaterdag</i> in Utrecht!</span></div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);"><span style="font-family: Arial, Helvetica, sans-serif;">
        </span></div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);"><span style="font-family: Arial, Helvetica, sans-serif;">Mozart heeft weliswaar 'slechts' 41 symfonieën geschreven, maar ook 20 pianoconcerten en tal van concerten voor viool, voor blazers en voor diverse combinaties van soloinstrumenten. Al die stukken hebben hun eigen charme én uitdagingen, maar de ervaring leert dat goed voorbereide spelers ze snel heel redelijk kunnen spelen. Daarbij helpt het als er in diverse groepen een professional (als aanvoerder) meespeelt. Met de concerten heb ik inmiddels veel ervaring door het <i>Mozart Concerto Event</i>, een onderdeel van mijn La Pellegrina zomercursus in Tsjechië. We organiseren daar een avond waarin deelnemers van de cursus</span><span style="font-family: Arial, Helvetica, sans-serif;">, bijvoorbeeld pianostudenten,</span><span style="font-family: Arial, Helvetica, sans-serif;"> een door hen </span><span style="font-family: Arial, Helvetica, sans-serif;">voorbereid</span><span style="font-family: Arial, Helvetica, sans-serif;"> </span><span style="font-family: Arial, Helvetica, sans-serif;">deel uit een concert spelen; de overige deelnemers vormen een orkest dat hen à vue begeleidt. Voor veel mensen is dat een kans die ze anders niet gauw krijgen en het </span><span style="font-family: Arial, Helvetica, sans-serif;">resultaat is </span><span style="font-family: Arial, Helvetica, sans-serif;">meestal verrassend goed.</span></div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);"><span style="font-family: Arial, Helvetica, sans-serif;">
        </span></div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);"><span style="font-family: Arial, Helvetica, sans-serif;">Ik heb in Utrecht de ideale repetitie- en concertruimte gevonden in het <a href="https://dhorringa-dot-yamm-track.appspot.com/2z7x6eXoeoTDUL9pKxk6nVyFLbQgd2Bfnbbysc3ieSiHdLpNalAG6Lh84vHpuXEcMqwxE30QJMUS2InjwK2HZqf0ftRzYEPSviaFpihDtASB4x51QufUbgFiuU1lrBa8slZk8NIsJThUnWM8ssngMdq9Zr-C8gB5bvWd3J6idNjAa5fKSEg" rel="nofollow" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://dhorringa-dot-yamm-track.appspot.com/2z7x6eXoeoTDUL9pKxk6nVyFLbQgd2Bfnbbysc3ieSiHdLpNalAG6Lh84vHpuXEcMqwxE30QJMUS2InjwK2HZqf0ftRzYEPSviaFpihDtASB4x51QufUbgFiuU1lrBa8slZk8NIsJThUnWM8ssngMdq9Zr-C8gB5bvWd3J6idNjAa5fKSEg&amp;amp;source=gmail&amp;amp;ust=1737561054419000&amp;amp;usg=AOvVaw1cVL_RHLHNCZ-HS7GfJi4i" style="color: rgb(17, 85, 204); cursor: pointer;">Stadsklooster</a>, een mooie, goed klinkende zaal (</span><span style="font-family: Arial, Helvetica, sans-serif;">een voormalige kerk</span><span style="font-family: Arial, Helvetica, sans-serif;">) met ook een vleugel. Het Stadsklooster ligt in de wijk Lombok, op nog geen kwartier lopen van het station. </span></div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);"><span style="font-family: Arial, Helvetica, sans-serif;">
        </span></div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);"><span style="font-family: Arial, Helvetica, sans-serif;">De eerste aflevering van <i>Mozart op Zaterdag</i> vindt plaats op <b>zaterdagochtend 22 feb</b></span><b>ruari</b>. We trappen af met <b>Mozarts 25e symfonie KV 183</b>. Het is een van de twee symfonieën in mineur die hij schreef. De andere is de beroemde 40e symfonie KV 550; beide staan in de dramatische toonsoort g-klein. Nr. 25 wordt daarom ook wel de ‘kleine g-mineur symfonie’ genoemd. Sinds de film Amadeus uitkwam, waarin in de opening de gejaagde muziek van het eerste deel klinkt, zou deze symfonie waarschijnlijk beter de 'Amadeus-symfonie' kunnen worden genoemd. Ik heb het stuk bijna veertig jaar geleden gedirigeerd bij mijn examen orkestdirectie bij David Porcelijn en heb daar bijzonder goede herinneringen aan. <a href="https://dhorringa-dot-yamm-track.appspot.com/2o-SKNyx5KLoUpMhCgjPlifhlH-ZBWgJCl0C8DRDWsj3jLpNalAGeKmDDd-CEkyR-wH57rm09TlRTGoT2N7zcIY4gMNSkPJ3MtOnZfh4av4huJkyiqoH-REY37KoKD9xJI2awaKBVfHbyytrmihtJPkLC87cMYBnvflhl2tY2CHLKN-g" rel="nofollow" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://dhorringa-dot-yamm-track.appspot.com/2o-SKNyx5KLoUpMhCgjPlifhlH-ZBWgJCl0C8DRDWsj3jLpNalAGeKmDDd-CEkyR-wH57rm09TlRTGoT2N7zcIY4gMNSkPJ3MtOnZfh4av4huJkyiqoH-REY37KoKD9xJI2awaKBVfHbyytrmihtJPkLC87cMYBnvflhl2tY2CHLKN-g&amp;amp;source=gmail&amp;amp;ust=1737561054419000&amp;amp;usg=AOvVaw0n5K1z_Ah9ZqEjwucBiMeB" style="color: rgb(17, 85, 204); cursor: pointer;">Een bijzonder fraaie uitvoering van het stuk is deze door Concentus Musicus Wien o.l.v. Harnoncourt</a>. De symfonie duurt ca. 27 minuten. De bezetting is 2 hobo's, 2 fagotten, 4 hoorns (waaronder moeilijke hoge partijen voor hoorn 1/2) en strijkers (ik denk aan 6.6.4.4.2).</div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">
    </div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">Qua tijden stel ik me dit voor: binnenkomen om 9:45, repeteren van 10:00 tot 12:30 met een korte pauze en dan om 13:00 een concertje van een half uur geven.</div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">
    </div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">Mijn vraag is nu: heb je belangstelling om mee te doen? We formeren een bezetting van serieuze en ervaren spelers die zich natuurlijk goed voorbereiden. Ik lever op tijd (betekende) partijen als PDF's aan. Deelname is gratis; wel wordt aan het eind om een vrijwillige bijdrage in de kosten van de zaal e.d. gevraagd. T.z.t. hoop ik de professionele deelnemers ook wat te kunnen betalen.</div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">
    </div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">Ik hoop dat je deze geweldige muziek met ons wilt spelen! <a href="https://dhorringa-dot-yamm-track.appspot.com/2B5tusjf07fxUgTXAyWlOcgJ6EAR2rRyhptHw7zpmnkfkLpNalAGV2H_YFge_mxArxGNpyx7v7GUGCEFtD6UljoM21yesHk2x0ZXIP6iPm0RO43v-T7zWGcGTXqNtBSnNxmurongtxELenwEbmU9DanJCtoEMz_MOQEBTKoPb7N_Yaa2nvqe15nuY" rel="nofollow" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://dhorringa-dot-yamm-track.appspot.com/2B5tusjf07fxUgTXAyWlOcgJ6EAR2rRyhptHw7zpmnkfkLpNalAGV2H_YFge_mxArxGNpyx7v7GUGCEFtD6UljoM21yesHk2x0ZXIP6iPm0RO43v-T7zWGcGTXqNtBSnNxmurongtxELenwEbmU9DanJCtoEMz_MOQEBTKoPb7N_Yaa2nvqe15nuY&amp;amp;source=gmail&amp;amp;ust=1737561054419000&amp;amp;usg=AOvVaw1KQdhlA92HWDYwjHBFm7cK" style="color: rgb(17, 85, 204); cursor: pointer;">In dit formulier kun je aangeven of je wilt meedoen</a>. Mogelijk zijn er meer inschrijvingen dan plaatsen. <b>Reageer daarom direct</b> (en niet later dan 19 januari); uiterlijk op 26 januari laat ik je weten of je geplaatst bent. </div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);"><span style="font-family: Arial, Helvetica, sans-serif;">
        </span></div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">Hartelijke groet</div>
    <font color="#888888" style="font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">
        <div class="gmail_default">
        </div>
        <div class="gmail_default">Dirkjan Horringa</div>
    </font>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">
    </div>
    <div class="gmail_default" style="color: rgb(34, 34, 34); font-family: tahoma, sans-serif; font-size: small; background-color: rgb(255, 255, 255);">P.S. het is de bedoeling hier een maandelijkse traditie van te maken op de vierde zaterdag van de maand. Dus de volgende keren zijn op 22 maart, 26 april en 24 mei. In het formulier kun je aangeven dat je voor die keren belangstelling hebt, ook als je op 22 februari niet kunt.</div>
</body>

</html>